FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel
RUN apt update
RUN apt install -y ffmpeg
RUN pip install uv fastapi uvicorn torch torchaudio pydub

RUN apt update && \
    apt install -y espeak-ng && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . ./
COPY api ./

RUN uv pip install --system -e .
RUN uv pip install --system -e .[compile]
RUN python3 download-model.py